import { Canvas } from '@react-three/fiber/native';
import React, { useMemo } from 'react';
import { StyleSheet, View } from 'react-native';
import { computeBlendShapeValues } from './src/character/blendShapeMapping';
import { CharacterViewer } from './src/character/CharacterViewer';
import { ANIMATION_CLIPS } from './src/character/constants';
import type { UserCharacterStats } from './src/character/types';

// Technical placeholder generated by tools/blender/generate_placeholder_character.py —
// not the commissioned art (see assets/characters/README.md). Swap for base_mesh.glb
// once the artist delivers it.
const BASE_MESH_URI = require('./assets/characters/base_mesh_placeholder.glb');

const MOCK_STATS: UserCharacterStats = {
  workout: {
    trainingConsistency: 0.6,
    upperBodyVolume: 0.4,
    chestVolume: 0.3,
    armVolume: 0.5,
    legVolume: 0.5,
  },
  body: {
    heightCm: 178,
    weightKg: 72,
    referenceHeightCm: 175,
    fatRatio: 0.35,
  },
  face: null,
};

export default function App() {
  const blendShapeValues = useMemo(() => computeBlendShapeValues(MOCK_STATS), []);

  return (
    <View style={styles.container}>
      <Canvas camera={{ position: [0, 1.6, 3], fov: 40 }}>
        <ambientLight intensity={0.6} />
        <directionalLight position={[2, 4, 3]} intensity={1.2} />
        <CharacterViewer
          baseMeshUri={BASE_MESH_URI}
          blendShapeValues={blendShapeValues}
          animation={ANIMATION_CLIPS.idle}
        />
      </Canvas>
    </View>
  );
}

const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: '#111' },
});
